### ISSUE TITLE
How's it going?

### ISSUE THREAD

**Issue by katieannemills** [dataopenspace/studyGroup#1]
Hi @dataopenspace , thanks for checking out the Mozilla Study Group project! How are thing going, does everything work for you? Please feel free to ask questions and post feedback in our [issue tracker](https://github.com/mozillascience/studyGroup/issues) - happy to help if I can!

**Comment by dataopenspace** [comment]
Thanks, it's great! Will definitely ping you with questions and feedback.

**Comment by katieannemills** [comment]
Awesome - going to close out here, but feel free to ping me any time.
