### ISSUE TITLE
event link is bouncing back to mozillascience

### ISSUE THREAD

**Issue by katieannemills** [dataopenspace/studyGroup#3]
The 16 May link on your [website](http://dataopenspace.github.io/studyGroup/) is bouncing back to the main mozilla science repo; to fix, open up an issue describing your event here, and link to that issue in your [event listing](https://github.com/dataopenspace/studyGroup/blob/gh-pages/_posts/2077-01-01-myEvent.markdown).

**Comment by dataopenspace** [comment]
Done :smile:
