### ISSUE TITLE
Data Open Space, May 16, Chicago

### ISSUE THREAD

**Issue by dataopenspace** [dataopenspace/studyGroup#4]
Let's get together to collaborate, work on projects, and talk about data.

**Comment by katieannemills** [comment]
Where / when?

**Comment by dataopenspace** [comment]
Should I be more specific. You mean like include the address of where we met?

**Comment by katieannemills** [comment]
If possible, but I see on your other meetup site you don't expose the meetup address to non-members. Which is totally fine - but it'll help newcomers get involved if there's some instructions on what you'd like them to do to make contact & find out the details of how to participate.

**Comment by dataopenspace** [comment]
Yes, I think what I'll do is match the event descriptions so that people who find us through various means will find the details here too.
